### ISSUE TITLE
Slack Login

### ISSUE THREAD

**Issue by michieriffic** [wwcodemanila/WWCodeManila-Hackathon-Site#1]
Login via Slack Group. :)

**Comment by kjcpaas** [comment]
ref: https://api.slack.com/docs/oauth

cc @amdg

**Comment by kjcpaas** [comment]
Nice app name `Hackambini` 😂 

![screencast](https://user-images.githubusercontent.com/3772828/32834966-692a46a6-ca3f-11e7-9c59-7ed9a4beec35.gif)

@amdg After authorizing, yung json lang mismo yung lumabas. Intended ba ito kasi wala pa yung page na makikita dapat ng participants?

PS: Disregard the error response kasi triny ko uli for screencast. Yung una, success response yung lumabas 😸

**Comment by amdg** [comment]
@kjcpaas Tracking your issue in #5
