### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by kjcpaas** [wwcodemanila/WWCodeManila-Hackathon-Site#3]
Auto build and deploy to Heroku app in https://github.com/wwcodemanila/WWCodeManila-Hackathon-Site/issues/2

**Comment by michieriffic** [comment]
@kjcpaas don't forget to give access to sa team sa heroku para maset up ng envars as needed. :) Salamat.

**Comment by kjcpaas** [comment]
Added na si @amdg. I-Slack mo sa akin email na gusto mo iadd ko.

**Comment by kjcpaas** [comment]
<img width="1044" alt="screen shot 2017-11-14 at 11 20 15 pm" src="https://user-images.githubusercontent.com/3772828/32787987-fb25ce7a-c992-11e7-8560-467d13ff78b2.png">

Nasetup ko na autodeploy to Heroku (`master` branch). Maglalagay ba tayo ng tests para kailangan ng CI? If not, okay na ito.

**Comment by kjcpaas** [comment]
Di na natin kailangan ng more sophisticated CI so enough na muna autodeploy sa Heroku.
